### ISSUE TITLE
AssertionError: failed to inspect the obj init

### ISSUE THREAD

**Issue by CreamyLong** [cplusx/layout_diffuse#2]
`python main.py -c configs/cocostuff_SD1_5.json`

got the error

> Traceback (most recent call last):
  File "main.py", line 38, in <module>
    ddpm_model = get_DDPM(
  File "/opt/data/private/layout_diffuse/train_utils.py", line 44, in get_DDPM
    ddpm_model = DDPM_model(
  File "/opt/data/private/layout_diffuse/DDIM_ldm/DDIM_ldm.py", line 555, in __init__
    super().__init__(
  File "/opt/data/private/layout_diffuse/DDIM_ldm/DDIM_ldm.py", line 415, in __init__
    super().__init__(
  File "/opt/data/private/layout_diffuse/DDIM_ldm/DDIM_ldm.py", line 234, in __init__
    self.call_save_hyperparameters()
  File "/opt/data/private/layout_diffuse/DDIM_ldm/DDIM_ldm.py", line 586, in call_save_hyperparameters
    self.save_hyperparameters(ignore=['denoise_fn', 'vqvae_fn', 'text_fn'])
  File "/root/anaconda3/lib/python3.8/site-packages/pytorch_lightning/core/mixins/hparams_mixin.py", line 105, in save_hyperparameters
    save_hyperparameters(self, *args, ignore=ignore, frame=frame)
  File "/root/anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/parsing.py", line 224, in save_hyperparameters
    assert init_args, "failed to inspect the obj init"
AssertionError: failed to inspect the obj init

**Comment by CreamyLong** [comment]
Could tell the version of pytorch-lightning?

**Comment by cplusx** [comment]
I am using pl version '1.9.3'
